name: "model_det"
platform: "tensorrt_plan"
max_batch_size: 32

input {
  name: "images"
  data_type: TYPE_FP32
  dims: [3, 640, 640] 
}

output {
  name: "output0"
  data_type: TYPE_FP32
  dims: [5, 8400] 
}

dynamic_batching { preferred_batch_size: [ 20 ] }

instance_group {
  kind: KIND_GPU
  count: 1
}