name: "model_seg"
platform: "tensorrt_plan"
max_batch_size: 200  # Must match max batch in trtexec

input [{
  name: "images"
  data_type: TYPE_FP32
  dims: [3, 320, 320]  # Omit batch dimension (handled by Triton)
}]

output [{
  name: "output0"
  data_type: TYPE_FP32
  dims: [37, 2100]  # Omit batch dimension (Triton adds it dynamically)
  },
  {
  name: "output1"
  data_type: TYPE_FP32
  dims: [32, 80, 80]  # Omit batch dimension (Triton adds it dynamically)
  }
]

dynamic_batching {
  preferred_batch_size: [1, 2, 4, 8, 16, 32, 64, 128, 200]
  max_queue_delay_microseconds: 500
}

instance_group {
  kind: KIND_GPU
  count: 1
}